feat: Issue 87 improve article design
lsglab/frontend pull request #88
Opened 2020-10-30 16:54 UTC by Flosi23

Ready to be merged into master

2020-10-31 20:56 UTC, GitGangGuy requested changes
Please switch from using url statements to resolve (which allows you to leave out the relative path, i.e. just say `resolve('arrow.png')`). This is in general a better idea than using `url` when importing static media. More documentation can be found [here](https://github.com/borodean/postcss-assets).

2020-11-01 16:22 UTC, jamwag approved these changes

2020-11-02 14:12 UTC, GitGangGuy commented
I will refactor some of the JS in my own branch, but this PR can be merged now.

2020-11-02 14:13 UTC, GitGangGuy approved these changes

2020-11-02 14:13 UTC, merged